### ISSUE TITLE
`yarn@4.0.0-rc.26` is not within ranage for `>=1.22.0`

### ISSUE THREAD

**Issue by kachkaev** [devoto13/yarn-plugin-engines#10]
Hi @devoto13! 👋 Thanks for this handy plugin! 💯

I just bumped Yarn from v3 to v4 RC using `yarn set version canary`:

```diff
-  "packageManager": "yarn@3.2.0",
+  "packageManager": "yarn@4.0.0-rc.26",
   "engines": {
     "node": "^16.14.0 || ^18.0.0",
     "yarn": ">=1.22.0"
   }
```

Running `yarn install` produced this:

```
➤ YN0000: ┌ Project validation
➤ YN0000: │ The current Yarn version 4.0.0-rc.26 does not satisfy the required version >=1.22.0.
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0s 3ms
```

Replacing `"yarn": ">=1.22.0"` with `"yarn": ">=1.22.0 || ^4.0.0-rc"` works but I wonder if this is expected behavior. WDYT?

**Comment by devoto13** [comment]
We use the `semver` package to check version ranges. Looks like this is the reasoning: https://github.com/npm/node-semver#prerelease-tags. It can be controlled by the `includePrerelease` setting, so should be pretty easy to change, but I'm not really sure if we should 🤔

**Comment by kachkaev** [comment]
I see! Feel free to close this issue if you think that the current behavior is correct. I’m happy both ways.

**Comment by devoto13** [comment]
I'll think about this a bit and then post back the final decision :)
