### ISSUE TITLE
Please release version with support for .node-version 

### ISSUE THREAD

**Issue by webervin** [devoto13/yarn-plugin-engines#14]
Following [install instructions](https://github.com/devoto13/yarn-plugin-engines/tree/main?tab=readme-ov-file#installation) does not include [Support .node-version too](https://github.com/devoto13/yarn-plugin-engines/commit/302ef2e986bde6d899a907347817fa2bbb92754b)  - potentially missing `yarn build` / or result of building not pushed to  [main branch](https://github.com/devoto13/yarn-plugin-engines/blob/main/bundles/%40yarnpkg/plugin-engines.js)

**Comment by devoto13** [comment]
Indeed, the updated bundle was not published. It should be fixed now.
