### ISSUE TITLE
Does not seem to check yarn version

### ISSUE THREAD

**Issue by kemsky** [devoto13/yarn-plugin-engines#3]
```json
  "engines": {
    "yarn": "bla-bla",
  }
```

**Comment by devoto13** [comment]
Can you describe a scenario where checking the `yarn` version would be useful? 

It will not work for Yarn 1 as the plugin is not invoked in that case. Yarn 2+ would normally have the binary committed to the repo making the check redundant. And for the [corepack](https://nodejs.org/api/corepack.html), there is already [`packageManager`](https://nodejs.org/api/packages.html#packagemanager) field to specify the version to be used, so the check is again redundant.

**Comment by devoto13** [comment]
Or is it for catching the cases where the user has 

```
 "engines": {
    "yarn": "1.22.17",
  }
```

but is actually running under Yarn 2+?

**Comment by kemsky** [comment]
@devoto13, yes, mostly this one

**Comment by romdej** [comment]
Hello, I see another use case where checking the yarn version would be useful: when updating yarn with `yarn set version`, the `packageManager` field is automatically updated with the new version. So anyone can update the version and there are no checks to prevent that change from being committed and deployed to other environments.

If you're ok, I can create a pull request to support it. @devoto13

**Comment by devoto13** [comment]
Sorry, this dropped off my radar a bit.
The `engines.yarn` should be supported in the latest version. Let me know if you experience any issues.
