### ISSUE TITLE
Allow ignoring check

### ISSUE THREAD

**Issue by 7rulnik** [devoto13/yarn-plugin-engines#9]
Engines are very useful in big companies with a lot of developers. We can make engines pretty strict, for example, allow only one exact version

```json
{
  "engines": {
    "node": "16.10.0"
  }
}
```

But sometimes we can't control the environment. For example within [renovate](https://hub.docker.com/layers/renovate/renovate/renovate/32.34.0/images/sha256-8151a0d7cd031f7eb3074a0de6d8545ab401cde7e745a57036eef7ae4068fb94?context=explore) which uses 14.19.1 right now. It would be nice if we can ignore engine checks sometimes. For example with the environment variable.

**Comment by devoto13** [comment]
This sounds like a good idea! 

I can look into it in the coming weeks. Or feel free to send a PR.

**Comment by 7rulnik** [comment]
Mention me if you will start working on it. I need to finish some other PRs :D

**Comment by devoto13** [comment]
Looks like Yarn considers any environment variables prefixed with `YARN_` as its configuration options and fails installation with:

> Unrecognized or legacy configuration settings found: pluginEnginesDisable - run "yarn config -v" to see the list of settings supported in Yarn.

Need to come up with a good name not starting with `YARN_`  I guess 😄

**Comment by teriu** [comment]
@devoto13 Did you need a hand with this? I wonder if we can use `PLUGIN_YARN_ENGINES_DISABLE` instead to prevent that name collision with `YARN_`.

**Comment by devoto13** [comment]
Was just not happy with all variants except the original one, so was thinking to wait until maybe Yarn removes the check on their side (it was only for migration from v1 AFAIU). But I guess it does not really matter that much. So will merge your PR, thanks!
